const Data = [
    {
        firstName : "Anis",
        lastName: "Kh",
        birthday:"17/02/1992",
        yearB:1992,
        gender:"male",
        email:"anis@anis.com",
        phone:"12345678",
        governerat:"tunis",
        school:"lycee technique tunis",
        college:"fsegt",
        studyCourse:"IT",
        facebook:"anis facebook",
        linkedin:"anis linkedin",
        program:[{training:"bloomasters", year:2017, project:"web application"}, {training:"boursier d'élite", year:2015}, {training:"spark", year:2012}],
        emailContact : "27/07/2017",
        profileUpdate: "12/02/2017",
        criteria:["hacker"]
    },
    {
        firstName : "Sofien",
        lastName: "ZZ",
        birthday:"25/02/1996",
        yearB:1996,
        gender:"male",
        email:"sofien@sofien.com",
        phone:"12345678",
        governerat:"gafsa",
        school:"Lycee Gafsa",
        college:"iset gafsa",
        studyCourse:"IT",
        facebook:"sofien facebook",
        linkedin:"sofien linkedin",
        program:[{training:"boursier d'élite", year:2012}],
        emailContact : "27/07/2017",
        profileUpdate: "12/02/2017",
        criteria:["hacker", "artist"]
    },
    {
        firstName : "Emna",
        lastName: "AA",
        birthday:"25/01/2004",
        yearB:2004,
        gender:"female",
        email:"emna@emna.com",
        phone:"12345678",
        governerat:"tunis",
        school:"lycee technique tunis",
        college:"",
        studyCourse:"",
        facebook:"emna facebook",
        linkedin:"emna linkedin",
        program:[ {training:"spark", year:2016}],
        emailContact : "27/07/2017",
        profileUpdate: "12/02/2017",
        criteria:["hacker", "artist"]
    },
    {
        firstName : "Khouloud",
        lastName: "CC",
        birthday:"25/03/1998",
        yearB:1998,
        gender:"female",
        email:"Khouloud@Khouloud.com",
        phone:"12345678",
        governerat:"bizerte",
        school:"lycee bizerte",
        college:"iset bizerte",
        studyCourse:"IT",
        facebook:"Khouloud facebook",
        linkedin:"Khouloud linkedin",
        program:[ {training:"boursier d'élite", year:2016},{training:"spark", year:2012}],
        emailContact : "27/07/2017",
        profileUpdate: "12/02/2017",
        criteria:["disciplinate", "strong temperament"]
    },
    {
        firstName : "Hela",
        lastName: "CC",
        birthday:"25/9/1990",
        yearB:1990,
        gender:"female",
        email:"hela@hela.com",
        phone:"12345678",
        governerat:"ben arous",
        school:"lycee ben arous",
        college:"enit",
        studyCourse:"IT",
        facebook:"hela facebook",
        linkedin:"hela linkedin",
        program:[{training:"bloomasters", year:2017, project:"web application"}, {training:"boursier d'élite", year:2014}],
        emailContact : "27/07/2017",
        profileUpdate: "12/02/2017"
    },
    {
        firstName : "Soumaya",
        lastName: "CC",
        birthday:"25/9/1992",
        yearB:1992,
        gender:"female",
        email:"soumaya@soumaya.com",
        phone:"12345678",
        governerat:"tabarka",
        school:"lycee technique tabarka",
        college:"enit",
        studyCourse:"IT",
        facebook:"hela facebook",
        linkedin:"hela linkedin",
        program:[{training:"bloomasters", year:2018, project:"web application"},{training:"spark", year:2013}],
        emailContact : "27/07/2017",
        profileUpdate: "12/02/2017",
        criteria:["disciplinate", "strong temperament", "artist"]
    },
]

export default Data